# Generated by Django 4.2.2 on 2023-06-14 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConfite',
            fields=[
                ('id', models.AutoField(db_column='CtgTpoCftID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='CtgTpoCftNom', max_length=50)),
            ],
            options={
                'db_table': 'CtgTpoCft',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(db_column='CtgProdCod', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='CtgProdNom', max_length=20)),
                ('imagen', models.ImageField(db_column='CtgProdImg', upload_to='catalogo/producto')),
                ('precio', models.PositiveIntegerField(db_column='CtgProdPre')),
                ('fch_elab', models.DateField(db_column='CtgProdFlb')),
                ('fch_vence', models.DateField(db_column='CtgProdFVen')),
                ('tipo', models.ForeignKey(db_column='CtgTpoCftID', on_delete=django.db.models.deletion.CASCADE, to='catalogo.tipoconfite')),
            ],
            options={
                'db_table': 'CtgProd',
            },
        ),
    ]
